apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-demo-deployment
  labels:
    app: app-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-demo
  template:
    metadata:
      labels:
        app: app-demo
    spec:
      containers:
      - name: app-demo
        image: kt-app-demo
        imagePullPolicy: Never
        env:
        - name: MOUNT_PATH
          value: "/mnt/data"
        ports:
        - containerPort: 8501
        volumeMounts:
          - mountPath: "/mnt/data"
            name: app-demo-volume
      volumes:
        - name: app-demo-volume
          persistentVolumeClaim:
            claimName: kt-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-service
  labels:
    app: app-demo
spec:
  type: ClusterIP
  # port is used to listen for incoming traffic from external clients
  # targetPort is the Service's internal communication port with the pods responsible for handling that traffic
  ports:
    - targetPort: 8501
      port: 8501
  selector:
    app: app-demo
